    - name: Download 
      ansible.builtin.get_url:
        url: https://github.com/keycloak/keycloak/releases/download/25.0.2/keycloak-25.0.2.zip
        dest: /opt/

    - name: Extract keycloak-25.0.2.zip into /opt/
      ansible.builtin.unarchive:
        src: /opt/keycloak-25.0.2.zip
        dest: /opt/

    - name: Create Folder for Cert
      command: mkdir /opt/keycloak-25.0.2/cert
