    - name: change Config - Keycloak
      template:                 
        src: "conf/keycloak.conf.j2"      
        dest: "/opt/keycloak-20.0.3/conf/keycloak.conf"
           
    - name: Get IP address
      shell: hostname -I
      register: ip_address

    - name: Update ip in keycloak.conf
      lineinfile:
        dest: /opt/keycloak-20.0.3/conf/keycloak.conf
        line: "ip = {{ ip_address.stdout_lines[0].strip() }}"
        state: present
        backrefs: yes
        regexp: "^ip = .*$"

    - name: Update hostname in keycloak.conf
      lineinfile:
        dest: /opt/keycloak-20.0.3/conf/keycloak.conf
        line: "hostname = {{ ip_address.stdout_lines[0].strip() }}"
        state: present
        backrefs: yes
        regexp: "^hostname = .*$"
        
    - name: Download export.sh
      template:
        src: "script/export.sh"
        dest: "/home/"

    - name: Script
      shell: bash export.sh
      args:
        chdir: /home/
