    - name: change Config - Keycloak
      template:                 
        src: "/conf/keycloak.conf.j2"      
        dest: "/opt/keycloak-20.0.3/conf/keycloak.conf"

    - name: Download export.sh
      template:
        src: "/script/export.sh"
        dest: "/home/"

    - name: Script
      shell: bash export.sh
      args:
        chdir: /home/
