---
- hosts: localhost
  connection: local
  become: true
  vars_files: 
    - task/vars/v.yml

  tasks:
    - include: task/1_pack.yml
    - include: task/2_keycloak.yml
    - include: task/3_postgresql.yml
    - include: task/4_openssl.yml
    #- include: task/49changeip.yml
    #- include: task/5_configip.yml
    - include: task/5_keyconfig.yml
    # - include: task/7_starkeycloak.yml
