- name: Update cache 
  apt:
    update_cache: yes

#- name: Upgrade all packages on servers
#  apt: 
#    name: "*"
#    state: latest

- name: Packages for Keycloak
  apt:
    name:
   # - mariadb-server
    #- mariadb-client
   # - mariadb-common
    - openjdk-17-jre-headless
    - unzip 
    #- python3
    #- python3-pip
    #- python3-mysqldb
    # - python-mysqldb
